// Dados mockados para teste da seção de metas

export const goalsMockData = [
  {
    id: 1,
    title: "Meta de Vendas Trimestral",
    description: "Alcançar a meta de vendas estabelecida para o trimestre atual, focando em novos clientes e expansão de contas existentes.",
    type: "Financeira",
    icon: "bx-money",
    periodType: "quarter",
    period: "Q4/2023",
    targetValue: 250000,
    currentValue: 185000,
    completion: 74,
    status: "in-progress",
    startDate: "2023-10-01",
    endDate: "2023-12-31",
    responsible: "Maria Souza",
    notes: "Estamos priorizando contas enterprise e expansão de contratos existentes.",
    createdAt: "2023-09-20",
    updatedAt: "2023-11-15"
  },
  {
    id: 2,
    title: "Aquisição de Novos Clientes",
    description: "Aumentar a base de clientes ativos através de estratégias de marketing e vendas otimizadas.",
    type: "Clientes",
    icon: "bx-user-plus",
    periodType: "month",
    period: "11/2023",
    targetValue: 50,
    currentValue: 37,
    unit: "clientes",
    completion: 74,
    status: "in-progress",
    startDate: "2023-11-01",
    endDate: "2023-11-30",
    responsible: "João Silva",
    notes: "Foco em campanhas de marketing digital e parcerias estratégicas.",
    createdAt: "2023-10-25",
    updatedAt: "2023-11-15"
  },
  {
    id: 3,
    title: "Receita Recorrente Anual",
    description: "Expandir a receita recorrente anual (ARR) através de novos contratos de assinatura e upsell para clientes existentes.",
    type: "Financeira",
    icon: "bx-refresh",
    periodType: "year",
    period: "2023",
    targetValue: 600000,
    currentValue: 450000,
    completion: 75,
    status: "in-progress",
    startDate: "2023-01-01",
    endDate: "2023-12-31",
    responsible: "Carlos Mendes",
    notes: "Meta estratégica alinhada com o objetivo de valorização da empresa.",
    createdAt: "2023-01-05",
    updatedAt: "2023-11-10"
  },
  {
    id: 4,
    title: "Lançamento de Novos Produtos",
    description: "Desenvolver e lançar novos produtos no mercado para diversificar as ofertas da empresa.",
    type: "Produtos",
    icon: "bx-package",
    periodType: "semester",
    period: "S2/2023",
    targetValue: 4,
    currentValue: 2,
    unit: "produtos",
    completion: 50,
    status: "in-progress",
    startDate: "2023-07-01",
    endDate: "2023-12-31",
    responsible: "Ana Pereira",
    notes: "Prioridade para produtos com maior margem de lucro e demanda de mercado.",
    createdAt: "2023-06-15",
    updatedAt: "2023-11-05"
  },
  {
    id: 5,
    title: "Redução de Churn Rate",
    description: "Reduzir a taxa de cancelamento de clientes através de estratégias de retenção e melhorias no atendimento.",
    type: "Clientes",
    icon: "bx-user-check",
    periodType: "quarter",
    period: "Q4/2023",
    targetValue: 5,
    currentValue: 8.2,
    unit: "%",
    completion: 30,
    status: "in-progress",
    startDate: "2023-10-01",
    endDate: "2023-12-31",
    responsible: "Pedro Lima",
    notes: "Implementar programa de fidelidade e melhorar suporte ao cliente.",
    createdAt: "2023-09-22",
    updatedAt: "2023-11-12"
  },
  {
    id: 6,
    title: "Implementação de CRM Avançado",
    description: "Migrar para um sistema de CRM mais avançado e treinar toda a equipe para utilização.",
    type: "Projetos",
    icon: "bx-task",
    periodType: "quarter",
    period: "Q1/2024",
    targetValue: 100,
    currentValue: 0,
    unit: "%",
    completion: 0,
    status: "upcoming",
    startDate: "2024-01-01",
    endDate: "2024-03-31",
    responsible: "Luiza Costa",
    notes: "Projeto crítico para melhorar eficiência de vendas e suporte.",
    createdAt: "2023-11-18",
    updatedAt: "2023-11-18"
  },
  {
    id: 7,
    title: "Meta de Vendas Regional Norte",
    description: "Expandir presença e vendas na região Norte do país.",
    type: "Vendas",
    icon: "bx-store",
    periodType: "year",
    period: "2023",
    targetValue: 180000,
    currentValue: 175000,
    completion: 97,
    status: "completed",
    startDate: "2023-01-01",
    endDate: "2023-12-31",
    responsible: "Rafael Gomes",
    notes: "Meta já praticamente concluída com sucesso.",
    createdAt: "2023-01-10",
    updatedAt: "2023-11-15"
  },
  {
    id: 8,
    title: "Expansão Internacional",
    description: "Iniciar operações em novos países da América Latina.",
    type: "Outro",
    icon: "bx-target-lock",
    periodType: "year",
    period: "2024",
    targetValue: 3,
    currentValue: 0,
    unit: "países",
    completion: 0,
    status: "upcoming",
    startDate: "2024-01-01",
    endDate: "2024-12-31",
    responsible: "Comitê Executivo",
    notes: "Prioridade para México, Colômbia e Chile conforme estudo de mercado.",
    createdAt: "2023-11-20",
    updatedAt: "2023-11-20"
  }
]; 